### ISSUE TITLE
Starší verse datovky a EOL u org.kde.Platform

### ISSUE THREAD

**Issue by dr47** [flathub/org.cznic.Datovka#10]
Flathub obsahuje starší versi Datovky (4.23.0), aktuálně je dostupná 4.23.7.

Také závislosti je potřeba aktualizovat:

`Informace: prostředí org.kde.Platform větev 6.5 je end-of-life, z důvodu:
   We strongly recommend moving to the latest stable version of the Platform and SDK
Informace: aplikace používající toto prostředí:
   org.cznic.Datovka
`

**Comment by Sesivany** [comment]
Z nějakého důvodu mi přestaly chodit upozornění na updaty Datovky z Release Monitoringu... Už dělám aktualizaci včetně aktualizací všech závislostí.

**Comment by Sesivany** [comment]
Aktualizace je venku, zavírám.
